/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    documents: Document;
    images: Image;
    users: User;
    invites: Invite;
    interviews: Interview;
    targetRoles: TargetRole;
    interviewers: Interviewer;
    tenants: Tenant;
    industries: Industry;
    levels: Level;
    roles: Role;
    challenges: Challenge;
    goals: Goal;
    companyTypes: CompanyType;
    institutionTypes: InstitutionType;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: "users";
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billingPlans".
 */
export interface BillingPlan {
  id: string;
  name: string;
  planId: string;
  price: number;
  price_formatted: string;
  interviewCount?: number | null;
  interviewDuration: number;
  freeTrialPeriod?: number | null;
  description?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  buy_now_url: string;
  planDuration?: number | null;
  expiredIn?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles?: ("platform-admin" | "platform-user")[] | null;
  name: string;
  phone?: string | null;
  language?: string | null;
  inviteToken: string;
  invitedUsers?: (string | User)[] | null;
  group?: (string | null) | Group;
  registeredAt?: string | null;
  reportAccess?: boolean | null;
  onboarding?: {
    persona?: ("student" | "professional" | "free") | null;
    industry?: (string | null) | Industry;
    targetRole?: {
      level?: (string | null) | Level;
      role?: (string | null) | Role;
    };
    challenge?: (string | Challenge)[] | null;
    trainingPlan?: {
      trainingType?: ("structured" | "freestyle") | null;
      hours?: number | null;
      mins?: number | null;
      per?: ("day" | "week" | "month") | null;
    };
    interviewDate?: string | null;
    cv?: (string | null) | Document;
  };
  freeTrialStartsAt?: string | null;
  freeTrialExpiresAt?: string | null;
  interviewPlan?: (string | null) | BillingPlan;
  interviewSubscriptionId?: string | null;
  interviewSubscriptionStatus?: string | null;
  interviewSubscriptionStartsAt?: string | null;
  interviewSubscriptionExpiresAt?: string | null;
  consultationPlan?: (string | null) | BillingPlan;
  consultationSubscriptionId?: string | null;
  consultationSubscriptionStatus?: string | null;
  consultationSubscriptionStartsAt?: string | null;
  consultationSubscriptionExpiresAt?: string | null;
  planUsage?: {
    usedInterviewTime?: number | null;
    usedConsultation?: number | null;
    usedConsultationTime?: number | null;
  };
  social?: {
    issuer?: ("google" | "facebook" | "linkedin" | "") | null;
    userId?: string | null;
  };
  picture?: string | null;
  entity?: {
    tenant?: (string | null) | Tenant;
    role?: ("owner" | "staff") | null;
  };
  notifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels".
 */
export interface Level {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: string;
  label: string;
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goals".
 */
export interface Goal {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  type?: (string | null) | InstitutionType;
  slug?: string | null;
  fromName?: string | null;
  fromAddress?: string | null;
  transportOptions?: {
    host?: string | null;
    port?: number | null;
    user?: string | null;
    pass?: string | null;
    secure?: boolean | null;
  };
  template?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: boolean | null;
  public?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutionTypes".
 */
export interface InstitutionType {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites".
 */
export interface Invite {
  id: string;
  to: string | User;
  token?: string | null;
  status?: ("pending" | "accepted" | "canceled") | null;
  accepts?: (string | User)[] | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews".
 */
export interface Interview {
  id: string;
  level?: (string | null) | Level;
  role?: (string | null) | Role;
  industry?: (string | null) | Industry;
  jobDescription?: string | null;
  companyInfo?: string | null;
  interviewLevel: "Newcomer" | "Rising Star" | "Pro Performer";
  focus: (
    | "Standard"
    | "Behavioral"
    | "Leadership"
    | "Situational"
    | "Technical Focus"
    | "Salary Negotiation"
  )[];
  interviewer: string | Interviewer;
  interviewee: string | User;
  chatHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  prompt: string;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "targetRoles".
 */
export interface TargetRole {
  id: string;
  level: string | Level;
  role: string | Role;
  industry: string | Industry;
  companyType: string | CompanyType;
  jobDescription?: string | null;
  companyInfo?: string | null;
  _user: string | User;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyTypes".
 */
export interface CompanyType {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group".
 */
export interface Group {
  id: string;
  name: string;
  creator: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviewers".
 */
export interface Interviewer {
  id: string;
  name: string;
  title?: string | null;
  description?: string | null;
  skills: {
    empathy: number;
    adaptability: number;
    patience: number;
    curiosity: number;
  };
  picture: string | Image;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "documents";
        value: string | Document;
      } | null)
    | ({
        relationTo: "images";
        value: string | Image;
      } | null)
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "invites";
        value: string | Invite;
      } | null)
    | ({
        relationTo: "interviews";
        value: string | Interview;
      } | null)
    | ({
        relationTo: "targetRoles";
        value: string | TargetRole;
      } | null)
    | ({
        relationTo: "interviewers";
        value: string | Interviewer;
      } | null)
    | ({
        relationTo: "tenants";
        value: string | Tenant;
      } | null)
    | ({
        relationTo: "industries";
        value: string | Industry;
      } | null)
    | ({
        relationTo: "levels";
        value: string | Level;
      } | null)
    | ({
        relationTo: "roles";
        value: string | Role;
      } | null)
    | ({
        relationTo: "challenges";
        value: string | Challenge;
      } | null)
    | ({
        relationTo: "goals";
        value: string | Goal;
      } | null)
    | ({
        relationTo: "companyTypes";
        value: string | CompanyType;
      } | null)
    | ({
        relationTo: "institutionTypes";
        value: string | InstitutionType;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
